2020-12-20 17:01:51,065 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:46]
2020-12-20 18:48:18,472 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:46]
2020-12-20 18:48:28,983 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:46]
2020-12-20 21:11:33,951 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:46]
2020-12-20 21:14:17,718 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:46]
2020-12-20 22:42:04,772 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:46]
2020-12-24 10:34:59,556 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:48]
2020-12-27 15:24:16,380 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:58]
2020-12-27 15:26:53,967 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:59]
2020-12-27 15:28:08,870 ERROR: Exception on /reset_password_request [POST] [in /home/albert/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/routes.py", line 218, in reset_password_request
    send_password_reset_email(user)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/email.py", line 45, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/models.py", line 84, in get_reset_password_token
    algorithm="HS256",
AttributeError: 'str' object has no attribute 'decode'
2020-12-27 15:29:07,789 ERROR: Exception on /reset_password_request [POST] [in /home/albert/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/routes.py", line 218, in reset_password_request
    send_password_reset_email(user)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/email.py", line 45, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/models.py", line 84, in get_reset_password_token
    algorithm="HS256",
AttributeError: 'str' object has no attribute 'decode'
2020-12-27 15:29:24,592 ERROR: Exception on /reset_password_request [POST] [in /home/albert/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/routes.py", line 218, in reset_password_request
    send_password_reset_email(user)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/email.py", line 45, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/models.py", line 84, in get_reset_password_token
    algorithm="HS256",
AttributeError: 'str' object has no attribute 'decode'
2020-12-27 15:32:23,093 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:59]
2020-12-27 15:32:35,613 ERROR: Exception on /reset_password_request [POST] [in /home/albert/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/routes.py", line 218, in reset_password_request
    send_password_reset_email(user)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/email.py", line 45, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/models.py", line 82, in get_reset_password_token
    {"reset_password": self.id, "exp": time() + expires_in},app.config["SECRET_KEY"],algorithm="HS256",).decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
2020-12-27 15:33:51,710 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:59]
2020-12-27 15:34:00,822 ERROR: Exception on /reset_password_request [POST] [in /home/albert/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/albert/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albert/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/routes.py", line 218, in reset_password_request
    send_password_reset_email(user)
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/email.py", line 45, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/albert/Documents/projects/flask_mega_tutorial/microblog/app/models.py", line 82, in get_reset_password_token
    {"reset_password": self.id, "exp": time() + expires_in}, app.config["SECRET_KEY"], algorithm="HS256").decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
2020-12-27 15:34:47,502 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:59]
2020-12-27 15:36:33,774 INFO: Microblog startup [in /home/albert/Documents/projects/flask_mega_tutorial/microblog/app/__init__.py:59]
